-- seeds for confessions

INSERT INTO confessions (user_id, category_id, content, created_at)
VALUES 
(1, 1, 'Lorem Ipsum oprogramowaniem przeznaczonym do realizacji druków na komputerach osobistych', 'a few seconds ago' ),
(2, 1, 'komputerach osobistych, jak Aldus PageMaker', 'a few seconds ago' ),
(3, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqu', 'a few seconds ago' ),
(3, 1, 'antium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt ', 'a few seconds ago' ),
(4, 1, 'oluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labor', 'a few seconds ago' ),
(1, 2, 'ptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur', 'a few seconds ago' ),
(1, 2, 'Tunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum', 'a few seconds ago' ),
(2, 2, 'i ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit am', 'a few seconds ago' ),
(3, 2, 'laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate', 'a few seconds ago' ),
(3, 2, ' totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto', 'a few seconds ago' ),
(2, 3, 'Have you ever cheated or did something improper at work (or school), or having lied to get a job (or into a school?)', 'a few seconds ago' ),
(3, 3, 'Have you ever hid a hobby or possession.', 'a few seconds ago' ),
(3, 3, 'ciunt. Neque porro quisquam est, qui dol', 'a few seconds ago' ),
(4, 3, ' aperiam, eaque ipsa quae ab i', 'a few seconds ago' ),
(4, 3, 'sequi nesciunt. Neque porro quisquam est', 'a few seconds ago' ),
(1, 1, 'I must confess content', 'a few seconds ago'),
(2, 2, 'Nothing meaningful content', 'a few seconds ago'),
(3, 3, 'Potatoes content', 'a few seconds ago'),
(4, 1, 'Apple something content', 'a few seconds ago'),
(5, 2, 'Whatever something content', 'a few seconds ago'),
(1, 1, 'Test Secret. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 1, 'Test Secret. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 1, 'Test Secret. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus. Sed tincidunt dictum arcu at semper.', 'a few seconds ago'),
(3, 1, 'Test Secret. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(4, 1, 'Test Secret. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'a few seconds ago'),

(1, 2, 'Test Story. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 2, 'Test Story. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 2, 'Test Story. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus. Sed tincidunt dictum arcu at semper.', 'a few seconds ago'),
(3, 2, 'Test Story. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(4, 2, 'Test Story. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'a few seconds ago'),

(1, 3, 'Test Question. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 3, 'Test Question. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(2, 3, 'Test Question. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus. Sed tincidunt dictum arcu at semper.', 'a few seconds ago'),
(3, 3, 'Test Question. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam luctus semper neque id rhoncus.', 'a few seconds ago'),
(4, 3, 'Test Question. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'a few seconds ago');