INSERT INTO options (poll_id, content)
VALUES 
(1, 'Once a year'),
(1, 'Every few months'),
(1, 'As much as possible'),
(1, 'Not anymore...'),
(2, 'Rarely'),
(2, 'once a while'),
(2, 'every single day'),
(3, 'yes'),
(3, 'no'),
(4, 'once'),
(4, 'never'),
(4, 'several times'),
(5, 'yes'),
(5, 'no'),
(6, 'dog'),
(6, 'cat'),
(6, 'both'),
(7, 'Marvel'),
(7, 'DC'),
(8, 'yes'),
(8, 'maybe'),
(8, 'no'),
(9, 'Tom Holland'),
(9, 'Chris Hemsworth'),
(9, 'Ryan Reynolds'),
(10, 'Beach'),
(10, 'Trekking'),
(10, 'Biking'),
(10, 'Go for a walk'),
(11, 'Coffee'),
(11, 'Tea'),
(11, 'Wine'),
(11, 'tea'),
(11, 'something else'),
(12, 'Cook'),
(12, 'take-out'),
(12, 'eat-out'),
(12, 'eat-frozen'),
(13, 'vacation'),
(13, 'staycation'),
(14, 'virtual'),
(14, 'in-person'),
(15, 'yes'),
(15, 'no'),
(16, 'yes'),
(16, 'no');